import { Recipe, RecipeBox, ItemCount, ItemStack } from "./Recipe.slint";
import { Button, VerticalBox, HorizontalBox, ScrollView} from "std-widgets.slint";
import { Header } from "Header.slint";
import { Hr } from "Hr.slint";

export component MainWindow inherits Window {
    in property <ItemStack> result;
    in property <[ItemStack]> raw_materials;
    in property <[ItemStack]> in_storage;
    in property <[Recipe]> steps;

    callback about_clicked <=> about-btn.clicked;
    callback set_target_clicked <=> set-target-btn.clicked;
    callback set_target(ItemStack);
    callback craft_clicked <=> craft-btn.clicked;
    callback craft(ItemStack);

    callback load_recipes_clicked <=> load-recipes-btn.clicked;
    callback save_recipes_clicked <=> save-recipes-btn.clicked;
    callback add_recipe_clicked <=> add-recipe-btn.clicked;
    callback add_recipe(Recipe);
    callback show_recipes_clicked <=> show-recipes-btn.clicked;

    callback add_resource_clicked <=> add-resource-btn.clicked;
    callback add_resource(ItemStack);
    callback remove_resource_clicked <=> remove-resource-btn.clicked;
    callback remove_resource(ItemStack);
    callback show_resources_clicked <=> show-resources-btn.clicked;

    callback load_resources_clicked <=> load-resources-btn.clicked;
    callback save_resources_clicked <=> save-resources-btn.clicked;

    title: "Crafting Calculator";
    preferred-width: 450px;
    preferred-height: 720px;

    ScrollView {
        VerticalLayout {
            alignment: start;
            padding-left: 5px;
            HorizontalBox {
                alignment: start;
                about-btn := Button {
                    text: "About";
                }
                set-target-btn := Button {
                    text: "Set Target";
                }
                craft-btn := Button {
                    text: "Craft Items";
                }
            }
            HorizontalBox {
                alignment: start;
                load-recipes-btn := Button {
                    text: "Load Recipes";
                }
                save-recipes-btn := Button {
                    text: "Save Recipes";
                }
                add-recipe-btn := Button {
                    text: "Add Recipe";
                }
                show-recipes-btn := Button {
                    text: "Show Recipes";
                }
            }
            HorizontalBox {
                alignment: start;
                add-resource-btn := Button {
                    text: "Add Resource";
                }
                remove-resource-btn := Button {
                    text: "Remove Resource";
                }
                show-resources-btn := Button {
                    text: "Show Resources";
                }
            }
            HorizontalBox {
                alignment: start;
                load-resources-btn := Button {
                    text: "Load Resources";
                }
                save-resources-btn := Button {
                    text: "Save Resources";
                }
            }

            VerticalLayout {
                Header { text: "Target:"; }

                Hr { }

                ItemCount {
                    items <=> root.result;
                }
            }

            Rectangle {
                border-color: transparent;
                border-width: 1px;
                height: 5px;
            }

            VerticalLayout {
                Header { text: "Raw materials:"; }

                Hr { }

                for material in raw-materials : ItemCount {
                    items: material;
                }
            }

            Rectangle {
                border-color: transparent;
                border-width: 1px;
                height: 5px;
            }

            VerticalLayout {
                Header { text: "In storage:"; }

                Hr { }

                for stack in in-storage : ItemCount {
                    items: stack;
                }
            }

            Rectangle {
                border-color: transparent;
                border-width: 1px;
                height: 5px;
            }

            VerticalLayout {
                Header { text: "Steps:"; }

                for recipe in steps : VerticalLayout {
                    alignment: start;
                    Hr { }
                    RecipeBox {
                        result: recipe.result;
                        method: recipe.method;
                        ingredients: recipe.ingredients;
                    }
                }
            }
        }
    }
}
