import { Recipe, RecipeBox, ItemCount, ItemStack } from "./Recipe.slint";
import { Button, VerticalBox, HorizontalBox, ScrollView} from "std-widgets.slint";

export component MainWindow inherits Window {
    in property <ItemStack> result;
    in property <[ItemStack]> ingredients;
    in property <[Recipe]> steps;

    callback about_clicked <=> about-btn.clicked;
    callback set_target_clicked <=> set-target-btn.clicked;
    callback set_target(ItemStack);
    callback craft_clicked <=> craft-btn.clicked;
    callback craft(ItemStack);

    callback load_recipes_clicked <=> load-recipes-btn.clicked;
    callback save_recipes_clicked <=> save-recipes-btn.clicked;
    callback add_recipe_clicked <=> add-recipe-btn.clicked;
    callback add_recipe(Recipe);
    callback show_recipes_clicked <=> show-recipes-btn.clicked;

    callback add_resource_clicked <=> add-resource-btn.clicked;
    callback add_resource(ItemStack);
    callback remove_resource_clicked <=> remove-resource-btn.clicked;
    callback remove_resource(ItemStack);
    callback show_resources_clicked <=> show-resources-btn.clicked;

    title: "Crafting Calculator";
    preferred-width: 450px;
    preferred-height: 720px;

    ScrollView {
        VerticalBox {
            HorizontalBox {
                vertical-stretch: 0;
                about-btn := Button {
                    horizontal-stretch: 0;
                    min-width: 0px;
                    min-height: 0px;
                    text: "About";
                }
                set-target-btn := Button {
                    horizontal-stretch: 0;
                    min-width: 0px;
                    min-height: 0px;
                    text: "Set Target";
                }
                craft-btn := Button {
                    horizontal-stretch: 0;
                    min-width: 0px;
                    min-height: 0px;
                    text: "Craft Items";
                }
                Text { horizontal-stretch: 1;}
            }
            HorizontalBox {
                load-recipes-btn := Button {
                    horizontal-stretch: 0;
                    min-width: 0px;
                    min-height: 0px;
                    text: "Load Recipes";
                }
                save-recipes-btn := Button {
                    horizontal-stretch: 0;
                    min-width: 0px;
                    min-height: 0px;
                    text: "Save Recipes";
                }
                add-recipe-btn := Button {
                    horizontal-stretch: 0;
                    min-width: 0px;
                    min-height: 0px;
                    text: "Add Recipe";
                }
                show-recipes-btn := Button {
                    horizontal-stretch: 0;
                    min-width: 0px;
                    min-height: 0px;
                    text: "Show Recipes";
                }
                Text { horizontal-stretch: 1; }
            }
            HorizontalBox {
                add-resource-btn := Button {
                    horizontal-stretch: 0;
                    min-width: 0px;
                    min-height: 0px;
                    text: "Add Resource";
                }
                remove-resource-btn := Button {
                    horizontal-stretch: 0;
                    min-width: 0px;
                    min-height: 0px;
                    text: "Remove Resource";
                }
                show-resources-btn := Button {
                    horizontal-stretch: 0;
                    min-width: 0px;
                    min-height: 0px;
                    text: "Show Resources";
                }
                Text { horizontal-stretch: 1;}
            }

            ItemCount {
                items <=> root.result;
            }

            for recipe in steps : Rectangle {
                border-color: gray;
                border-width: 2px;
                vertical-stretch: 0;
                RecipeBox {
                    result: recipe.result;
                    method: recipe.method;
                    ingredients: recipe.ingredients;
                }
            }

            Text { vertical-stretch: 1; }
        }
    }
}
