import { VerticalBox, HorizontalBox } from "std-widgets.slint";

export struct ItemStack {
    name: string,
    count: int,
}

export struct Recipe {
    result: ItemStack,
    method: string,
    catalysts: [ItemStack],
    ingredients: [ItemStack],
}

export component ItemCount inherits HorizontalLayout {
    in property <ItemStack> items;
    in property <int> indent_level;

    alignment: start;
    padding: 0px;
    padding-left: (root.indent-level + 1) * 5px;
    Text {
        text: items.count > 0 ? "\{items.name} x\{items.count}" : "";
    }
}

export component RecipeBox inherits VerticalLayout {
    in property <ItemStack> result;
    in property <string> method;
    in property <[ItemStack]> ingredients;

    alignment: start;
    padding: 5px;
    HorizontalLayout {
        alignment: start;
        padding-left: 0px;
        ItemCount {
            items: result;
            indent-level: 0;
        }
        Text {
            text: " (\{root.method})";
        }
    }
    for ingredient in ingredients : ItemCount {
        indent-level: 1;
        items: ingredient;
    }
}
