import { ItemStack, Recipe, RecipeBox } from "./Recipe.slint";
import { StandardButton , VerticalBox, ScrollView, HorizontalBox, LineEdit} from "std-widgets.slint";

export component Recipes inherits Dialog {
    in property <[Recipe]> recipes;
    title: "Recipes";
    min-height: 240px;
    min-width: 360px;

    callback search-edited <=> search-box.edited;

    VerticalLayout {
        search-box := LineEdit {
            placeholder-text: "Search recipes...";
        }
        ScrollView {
            VerticalLayout {
                for recipe in recipes : RecipeBox {
                    result: recipe.result;
                    method: recipe.method;
                    ingredients: recipe.ingredients;
                }
            }
        }
    }
    StandardButton { kind: close; }
}
