import { ItemStack } from "./Recipe.slint";
import { StandardButton , VerticalBox, ScrollView, HorizontalBox, LineEdit} from "std-widgets.slint";

export component Resources inherits Dialog {
    in property <[ItemStack]> resources;
    title: "Resources";
    min-height: 240px;
    min-width: 360px;

    callback search-edited <=> search-box.edited;

    VerticalLayout {
        search-box := LineEdit {
            placeholder-text: "Search resources...";
        }
        ScrollView {
            VerticalLayout {
                for resource in resources : HorizontalLayout {
                    Text { text: resource.name; }
                    Text { text: "x\{resource.count}"; }
                }
            }
        }
    }
    StandardButton { kind: close; }
}
