import { HorizontalBox, LineEdit, SpinBox, StandardButton } from "std-widgets.slint";

export component ResourceDialog inherits Dialog {
    in property <bool> add_resource;
    out property <string> item_name <=> name.text;
    out property <int> item_count <=> count.value;

    callback cancel_clicked <=> cancel-btn.clicked;
    callback ok_clicked <=> ok-btn.clicked;

    title: add_resource ? "Add Resource" : "Remove Resource";
    forward-focus: name;
    FocusScope {
        HorizontalBox {
            name := LineEdit {
                enabled: true;
                accepted => { root.ok_clicked(); }
            }
            count := SpinBox {
                enabled: true;
                minimum: 1;
                maximum: 2147483647;
                horizontal-stretch: 0;
            }
        }
        key-pressed(event) => {
            if (event.text == Key.Escape) {
                root.cancel_clicked();
                accept
            } else if (event.text == Key.Return) {
                root.ok_clicked();
                accept
            } else {
                reject
            }
        }
    }

    cancel-btn := StandardButton { kind: cancel; }
    ok-btn := StandardButton { kind: ok; }
}
